@API = http://localhost:3400

### POSTS
GET {{API}}/posts

### POST
GET {{API}}/post/1

### CREATE
POST {{API}}/createposts
Content-Type: application/json

{
    "id": 0,
    "title": "Third title",
    "content": "Third content",
    "created": 0
}

### REMOVE
DELETE {{API}}/removeposts/7

### UPDATE
PUT {{API}}/updateposts/17
Content-Type: application/json

{
    "title": "update title",
    "content": "update content",
    "created": 0
}